# Generated by Django 2.0.5 on 2020-02-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenzie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=25)),
                ('descriere', models.CharField(max_length=255)),
                ('data_adaugari', models.DateTimeField()),
                ('masina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masina.Masini')),
            ],
        ),
    ]
