# Generated by Django 2.0.5 on 2020-03-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reprezentanta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('pret', models.FloatField()),
                ('reprezentanta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reprezentanta.Reprezentanta')),
            ],
        ),
    ]
