# Generated by Django 2.0.5 on 2020-03-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='masina/')),
                ('masina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masina.Masini')),
            ],
        ),
    ]
